### ISSUE TITLE
Post-installation camera information

### ISSUE THREAD

**Issue by magarto** [Boltgolt/howdy-reports#2]
Video devices [IR=0]
```
video0
```
Lsusb output
```
      iFunction               4 HD WebCam
        wTerminalType      0x0201 Camera Sensor
```
Udevadm
```
E: ID_BUS=usb
E: ID_MODEL=HD_WebCam
E: ID_MODEL_ENC=HD\x20WebCam
E: ID_MODEL_ID=b5f7
E: ID_V4L_PRODUCT=HD WebCam: HD WebCam
E: ID_VENDOR_ID=04f2
```

**Comment by magarto** [comment]
"sudo howdy USER add" worked but script doesn't work due to error with cv2. Already reported in issues.

**Comment by Boltgolt** [comment]
Great, thanks! It seems you only have 1 camera, are you sure it is the IR one? Udevadmn data doesn't sound like an IR camera either.

**Comment by magarto** [comment]
Yes, it is. Works like a charm
