### ISSUE TITLE
Post-installation camera information

### ISSUE THREAD

**Issue by lcseguin** [boltgolt/howdy-reports#21]
Video devices [IR=0]
```
video0
```
Lsusb output
```
  iProduct                1 Integrated Camera
    iConfiguration          4 USB Camera
      iFunction               5 Integrated Camera
      iInterface              5 Integrated Camera
        wTerminalType      0x0201 Camera Sensor
```
Udevadm
```
E: ID_BUS=usb
E: ID_MODEL=Integrated_Camera
E: ID_MODEL_ENC=Integrated\x20Camera
E: ID_MODEL_ID=b604
E: ID_V4L_PRODUCT=Integrated Camera: Integrated C
E: ID_VENDOR_ID=04f2
```

**Comment by boltgolt** [comment]
Thanks for posting your webcam information! I'd like to add support for a wider range of cameras in howdy and details about the working models help a lot. 

If you have any problems or suggestions don't hesitate to open an issue in the [main repository](https://github.com/Boltgolt/howdy).
