### ISSUE TITLE
Post-installation camera information

### ISSUE THREAD

**Issue by Jerezano** [Boltgolt/howdy-reports#3]
Video devices [IR=0]
```
video0
```
Lsusb output
```
      iFunction               4 Integrated Webcam
        wTerminalType      0x0201 Camera Sensor
```
Udevadm
```
E: ID_BUS=usb
E: ID_MODEL=Integrated_Webcam_HD
E: ID_MODEL_ENC=Integrated_Webcam_HD
E: ID_MODEL_ID=28ae
E: ID_V4L_PRODUCT=Integrated_Webcam_HD: Integrate
E: ID_VENDOR_ID=1bcf
```

**Comment by Boltgolt** [comment]
Thanks posting your debug info! I'd like to add support for a wider range of cameras and details about the working models help a lot. 

If you have any problems or suggestions don't hesitate to open an issue in the [main repository](https://github.com/Boltgolt/howdy).
