### ISSUE TITLE
Post-installation camera information

### ISSUE THREAD

**Issue by alextelfer** [Boltgolt/howdy-reports#9]
Video devices [IR=0]
```
video0
```
Lsusb output
```
    iConfiguration          4 USB Camera
      iFunction               5 USB2.0 UVC HD Webcam
        wTerminalType      0x0201 Camera Sensor
```
Udevadm
```
E: ID_BUS=usb
E: ID_MODEL=USB2.0_UVC_HD_Webcam
E: ID_MODEL_ENC=USB2.0\x20UVC\x20HD\x20Webcam
E: ID_MODEL_ID=9700
E: ID_V4L_PRODUCT=USB2.0 UVC HD Webcam: USB2.0 UV
E: ID_VENDOR_ID=064e
```

**Comment by Boltgolt** [comment]
Thanks for posting your webcam information! I'd like to add support for a wider range of cameras in howdy and details about the working models help a lot. 

If you have any problems or suggestions don't hesitate to open an issue in the [main repository](https://github.com/Boltgolt/howdy).
